### ISSUE TITLE
Setup crashed failing to load "libcurl.dll"

### ISSUE THREAD

**Issue by elliottedward327** [spikespaz/search-deflector#1]
```
Welcome to Search Deflector setup.
Just answer the prompts in this terminal to set your preferences, and you should be good to go.
If you have any questions, please email me at 'support@spikespaz.com',
or create an Issue on the GitHub repository (https://github.com/spikespaz/search-deflector/issues).


The SearchDeflector setup has crashed. Try running the executable as administrator.
If the problem persists, please copy the error below and submit an issue on GitHub.
https://github.com/spikespaz/search-deflector/issues

=== BEGIN CRASH EXCEPTION ===

std.net.curl.CurlException@std\net\curl.d(4169): Failed to load curl, tried "libcurl.dll", "curl.dll".
----------------
0x00407D95
0x0041DC4A
0x0041DBAA
0x6C6C642E
0xCCCCCC00
0xB81CEC83
0x004DBA70
0x04245C89
0x6F6C675F
0x5F6C6162
0x74696E69 in Ordinal823

=== END CRASH EXCEPTION ===

Search Deflector setup completed. You may now close this terminal.
Press Enter to exit.
```

**Comment by spikespaz** [comment]
Well that was a fucking failure.

**Comment by spikespaz** [comment]
I've updated the download to include the missing DLL file for curl. It should now be able to successfully make HTTP requests. https://github.com/spikespaz/search-deflector/releases/download/0.0.1/SearchDeflector-0.0.1.zip

Just extract the executable to somewhere safe as described in the README.md.

This issue still is not resolved because I would like to dynamically dump the byte content of the DLL to eliminate any dependencies, or use a resource file. Maybe even making a separate installer executable would be sufficient.

**Comment by spikespaz** [comment]
Removing bug label because this was never really a bug. If you use the new installer, the dependencies are taken care of for you. Look at the updated [README.md](README.md) for the updated instructions.
