### ISSUE TITLE
Virus detected? Trojan:Win32/Zpevdo.A

### ISSUE THREAD

**Issue by mrkhew** [spikespaz/search-deflector#37]
Is this program safe? Detected by Windows Defender as follows:

![annotation](https://user-images.githubusercontent.com/31813140/47592567-63fb1d00-d9a6-11e8-8e09-50583e3e1e59.png)

**Comment by spikespaz** [comment]
This program is absolutely safe, you can view the source code yourself to verify this. In fact, the fact that you are getting this error is strange to me because I just finished publishing it on the Microsoft Store [here](https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K) and Microsoft employees had to manually approve my program for certification.

I also checked the `deflector.exe` file that I'm distributing on GitHub with VirusTotal. It for some reason has 10 engines detected. I don't know why, I'm sorry. [This](https://github.com/spikespaz/search-deflector/blob/master/source/deflector.d) is the source code for that file, it literally just parses a string.

**Comment by mrkhew** [comment]
> 
> 
> This program is absolutely safe, you can view the source code yourself to verify this. In fact, the fact that you are getting this error is strange to me because I just finished publishing it on the Microsoft Store [here](https://www.microsoft.com/store/productId/9P8ZJJ80RZ2K) and Microsoft employees had to manually approve my program for certification.
> 
> I also checked the `deflector.exe` file that I'm distributing on GitHub with VirusTotal. It for some reason has 10 engines detected. I don't know why, I'm sorry. [This](https://github.com/spikespaz/search-deflector/blob/master/source/deflector.d) is the source code for that file, it literally just parses a string.

I've go thru the source and doesn't found anything strange too, maybe it's false postive result.
Attached [Virus Total](https://www.virustotal.com/#/file/510eede6edb2275e043b61418c92e7dafecb8267cbbb1d122b763af977d8e474/detection)

**Comment by spikespaz** [comment]
Do you mind if I use your screenshot add some relevant information about this to [the Wiki](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting) Troubleshooting section?

If I add it to the Wiki I will close this issue.

**Comment by mrkhew** [comment]
No problem, you may use it

**Comment by spikespaz** [comment]
Added a new section to the [wiki](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#blocked-by-antivirus).

**Comment by spikespaz** [comment]
Link to newer duplicate issue: https://github.com/spikespaz/search-deflector/issues/53
