### ISSUE TITLE
Missing vcruntime140.dll error during setup with version 1.0.0

### ISSUE THREAD

**Issue by KyloJorgensen** [spikespaz/search-deflector#47]
![image](https://user-images.githubusercontent.com/18789138/51875743-023aae00-231b-11e9-9048-d4338686389f.png)
Git this erro installing version 1.0.0 version 0.3.6 still works great.

**Comment by spikespaz** [comment]
Well, since 0.3.6 and 1.0.0 are exactly the same functionally, I have no clue why this is.

Could you please report a list of all of the C++ redistributable packages you have installed on your system?

Please uninstall any version of Search Deflector that you have installed and try again, with each version.

**Comment by KyloJorgensen** [comment]
I do use C++ for school. So let me try that and get back to you

**Comment by spikespaz** [comment]
@KyloJorgensen It's been a while since you replied. Any update?

**Comment by spikespaz** [comment]
This can be reopened when @KyloJorgensen responds, or if someone creates a duplicate or replies to this one.

**Comment by Vas0sky** [comment]
I have the exact same issue. I tried on a fresh install (no programs installed, no C++ Redistributables), 1.0.0 complains about the dll missing while 0.3.6 works just fine.

**Comment by spikespaz** [comment]
@Vas0sky I don't know why these problems are cropping up by the addition of an image to the installer. It has to be a problem with Inno setup. I could remove the image, but I'd be sad to do so, because I like the way it looks. I'll take a look and see if it's something that can be resolved. I suppose most people are assumed to already have a CPP Redistributable installed.

**Comment by Vas0sky** [comment]
I've also tried installing Visual Studio 2017 C++ x64 Redistributables and the error still occurs.

**Comment by bernstein82** [comment]
I have the same problem. Both with the appx-Package as well as the Installer

**Comment by spikespaz** [comment]
This is all very, very strange. I wonder, could it be the compiler's fault? Food for thought. I'll look into it.

**Comment by spikespaz** [comment]
I'm going to build several versions. I would appreciate if a few of you could take the time to test them out for me, I know it's a lot to ask. I just need to find the root cause of the problem.

I'll throw in a bonus: two keys for the store version (one for a friend). If you already own the store version, I'll refund it as well.

| Compiler Version | Link         |
| ---------------- | ------------ |
| LDC 1.15.0-beta2 | [:link:][10] |
| LDC 1.14.0       | [:link:][11] |
| LDC 1.13.0       | [:link:][12] |
| LDC 1.12.0       | [:link:][13] |

For each version in the table, download an install it, and make sure that the setup and the search works. Before installing each version however, uninstall the previous. Just reply back with what works and what doesn't, and what happens instead for each build.

The password for all of the files is `issue47`. The download links will all expire seven days from the time of this post.

Thanks!

[10]: https://send.firefox.com/download/5c4d67d9570267e0/#7wluLpp5EdFBjEZvP3uP6A
[11]: https://send.firefox.com/download/b24f9382de34e24d/#EdOnAXgPuA__-NSD7uTOYA
[12]: https://send.firefox.com/download/b022c0a6f49e7a7e/#GcSuFpYTWyKrbFWrBBDqRQ
[13]: https://send.firefox.com/download/9433b92726bf8610/#XMbOpGZXI4vseRJZwvhQSQ

**Comment by spikespaz** [comment]
@KyloJorgensen @Vas0sky @bernstein82

**Comment by roadrunnor** [comment]
so any news about that dev issue?

**Comment by spikespaz** [comment]
@roadrunnor No, I didn't get any responses from anyone so I don't know what to fix. I've updated the links in the other comment so that the files can still be downloaded.

**Comment by spikespaz** [comment]
A new update just rolled out. If you've selected the updater module when you installed it, you should automatically get the new version after 12:00am. It's compiled with LDC 1.15.0-beta2, I forgot to update my compiler. But I hope this one works. Let me know if it starts working for you all in a few days.

Thanks.

**Comment by spikespaz** [comment]
I finally got my hands on a computer afflicted by this issue. The solution was as simple as downloading the latest 32-bit redistributable from Microsoft.

Please download the latest (x86) [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), install it, and run the "Configure" shortcut from your start menu.

That should be all that is required. If this doesn't fix the issue, let me know and I will re-open.
