### ISSUE TITLE
Installation fails with "code 1450", unable to execute configure.exe

### ISSUE THREAD

**Issue by ftlbiped** [spikespaz/search-deflector#55]
## Bug Description

When attempting to install search deflector, I get an error

> Unable to execute file
> C:\Program Files (x86)\Search Deflector\configure.exe
> CreateProcess failed; code 1450.
> Insufficient system resources exist to complete the requested service

I thought this might be related to #48 which also has an error that refers to lack of system resources, but the error message is different and - more saliently - trying the workaround for that issue which is described on the wiki doesn't work for me. I can download and install version 0.3.6, and trigger the force update, but the configure window that comes up when following the last step is still the one for 0.3.6, not for 1.1.5 as I'd expect if the fix had worked.

## How to Reproduce

**To get the original bug** Download and run the installer for v1.1.5

**To see that the fix on the wiki doesn't work** Download and run the installer for 0.3.6, then follow the [instructions on the wiki page](https://github.com/spikespaz/search-deflector/wiki/Troubleshooting#installer-crashes-with-out-of-system-resources-error). 

## Screenshots

![image](https://user-images.githubusercontent.com/12207972/68092787-d70e5d80-fe5c-11e9-91e2-bc5263a08606.png)

## Environmental Details

| Windows Version | `1903` |
| --- | --- |
| Build Number | `18362.418` |
| Insiders Preview | No |

It may be a coincidence, but I'm on a very similar machine to that of the user who filed #48 : HP Spectre x360 w/ i7 processor, 16 GB RAM, 512 GB SSD.

**Comment by spikespaz** [comment]
I haven't responded because there isn't really anything I can do about this. It's an error that specifically occurs on your machine.

According to the [system error codes](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-) list from Microsoft, 1405 happens when there is an "invalid handle to a multiple-window position structure" which is the responsibility of the installer, created by Inno Setup.

The best guess I have is that it has something to do with display scaling, it looks like your Spectre is using something above 100% to compensate for the pixel density of your screen. I would be curious to know if changing that would make any difference; although I have no idea why it would.

It wouldn't surprise me if restarting the machine and trying again later would fix the issue.

**Comment by spikespaz** [comment]
The workaround on the wiki that involves installing 0.3.6 first does indeed still work work when updating to the latest (1.1.5) as of writing. I suspect that you didn't complete the setup in Command Prompt and close the installer completely before running the legacy "Force Update".

**Comment by spikespaz** [comment]
If you still are affected by this issue or if anyone else is this can be opened again.
