### ISSUE TITLE
Fix "Search Deflector" app in Task Scheduler 

### ISSUE THREAD

**Issue by xmha97** [spikespaz/search-deflector#60]
Hello,

"Search Deflector" app adding in Task Scheduler like below image:

![image](https://user-images.githubusercontent.com/23485114/77466886-94a7e600-6e28-11ea-98d5-23adec361520.png)

Please fix it.

![image](https://user-images.githubusercontent.com/23485114/77467091-f6685000-6e28-11ea-9ceb-0556f9043212.png)

Why?
Because clean up software will delete it.

![image](https://user-images.githubusercontent.com/23485114/77467138-1435b500-6e29-11ea-891c-a441a43dd5bc.png)

Thanks

**Comment by spikespaz** [comment]
Huh. I'll take a look, thanks!

**Comment by spikespaz** [comment]
The installer seems to work fine on three of my computers. Please uninstall and try again, let me know if this persists. But if it's a fluke it isn't my bug.

**Comment by xmha97** [comment]
I reinstall it on my PC and Laptop but this persists.
![image](https://user-images.githubusercontent.com/23485114/77615433-08dbaa00-6f4d-11ea-8fb9-7ef6f1b61f2f.png)

**Comment by xmha97** [comment]
Please delete "Search Deflector" from Task Scheduler and install again.

**Comment by xmha97** [comment]
> The installer seems to work fine on three of my computers. Please uninstall and try again, let me know if this persists. But if it's a fluke it isn't my bug.

I reinstall it on my PC and Laptop but this issue persists.
Please delete "Search Deflector" from Task Scheduler and install again.

**Comment by xmha97** [comment]
I think if you add `"`, this issue fixed.
PLACEHOLDER -> "PLACEHOLDER"
![image](https://user-images.githubusercontent.com/23485114/77616133-9075e880-6f4e-11ea-839b-f41b534b234f.png)

**Comment by spikespaz** [comment]
I know it's been a long time since this issue was opened, but I assume that you have solved it for yourself? The scheduler task seems to work on every other machine that has been tested on so there's some outlier circumstances that prevented it from being registered properly on your system. The changes with quotations will not be made because the `PLACEHOLDER` string is there for replacement only. If the issue ersists please let me know and re-open.
