### ISSUE TITLE
After clicking one of search results from UI, browser still brings me to the search result listing

### ISSUE THREAD

**Issue by jj1118** [spikespaz/search-deflector#63]
## Bug Description

Understand that the UI is hardcoded to stick to showing Bing results by Microsoft (https://github.com/spikespaz/search-deflector/issues/49). However, when I do decide that Bing already fetches what I need by following one of the results shown (instead of immediately pressing Enter after typing my query which should open my default browser & search engine), the browser is expected to open that link. This is not the case as of v1.1.6 as Chrome still opens Google result list with a most likely different ordering, interrupting my navigation.

## How to Reproduce

**Browser**: Google Chrome

**Search Engine:** Google

**Steps to reproduce the behavior:**

1. Type any query into the search box.
2. Wait a few seconds for Bing results to show up in the right panel.
3. Click on one of the search results.

## Expected Behavior

The default browser should directly open that link instead of displaying the result list of the default search engine.

## Environmental Details

Press <kbd>Win</kbd><kbd>R</kbd> and type `winver` and then <kbd>Enter</kbd>. Copy the relevant information to the table below. Everyone submitting a bug report **must** complete this section.

| Windows Version | 1909 |
| --- | --- |
| Build Number | 18363.778 |
| Insiders Preview | No |

**Comment by spikespaz** [comment]
Thank you for a glowing example of the kind of bug report I would like to see, with all of the details and everything that tell me exactly what is going on with concise description. That that title. Nice. 👌 

More to the point however, I did notice this issue myself a while ago and just never bothered to fix it because I don't look at the Bing results and nobody cared to complain about it. Now that you've tried to use it and have noticed it isn't working I'll look into it.

**Edit:** Closed by mistake.

**Comment by spikespaz** [comment]
Fixed by https://github.com/spikespaz/search-deflector/commit/cb3d6adb02bf6d78792c122f895b1d5fe8e1f67f, the patch will be shipped with 1.3.2.
