### ISSUE TITLE
After being blocked by Malwarebytes and added to the exclusion list, it no longer works.

### ISSUE THREAD

**Issue by amminadabz** [spikespaz/search-deflector#64]
First, Malwarebytes blocked the installer, so I added it to the exclusion list. I installed it succesfully and ran a test search. When it prompted me to choose an app to complete the search, I chose Search Deflector, but I did not click the checkbox for "Use every time" or "Set as default" or whatever it is called. I assumed I would be able to set it as default after I had seen what it could do. After choosing Search Deflector is when Malwarebytes blocked it again, so I went back to the exclusion list and added the Search Deflector folder in "Program Files (x86)". However, when I tried another search, I was not presented with the option to use Search deflector, and the search opened with Bing on Edge. 
I have tried uninstalling and reinstalling.

**Comment by spikespaz** [comment]
This is strange. Did you make sure MBAM put the files back where the registry and shortcuts expect them to be? Where I designed them to be?

**Comment by amminadabz** [comment]
I think so. Here's what the folder looks like.
<img width="647" alt="search deflector screenshot" src="https://user-images.githubusercontent.com/51542239/82976559-06c1b600-9fa5-11ea-8c21-7d94a9979fac.png">

**Comment by spikespaz** [comment]
This looks correct. Make sure that Search Deflector is selected as the default handler for `MICROSOFT-EDGE`, go to Settings > Apps > Default apps > Choose default apps by protocol, and align what you see with this.
![image](https://user-images.githubusercontent.com/12502988/82997861-c91c5780-9fbb-11ea-9c93-428b93b510db.png)

Also make sure that you have something other than Edge Chromium as default browser because there is a known conflict that will take a rewrite to fix.

**Comment by amminadabz** [comment]
That fixed it. Thanks a bunch!
