### ISSUE TITLE
Wiki: "Setup & Installing" can't be viewed/accessed

### ISSUE THREAD

**Issue by CoreyVidal** [spikespaz/search-deflector#65]
## Bug Description

I am unable to view the "Setup & Installing" page in the Wiki section of the search-deflector GitHub repository. It forwards me to [the root of the Wiki](https://github.com/spikespaz/search-deflector/wiki). It then displays a banner warning at the top of the page, saying:

You do not have permission to update this wiki.

If I try while not logged in, no banner is shown.

## How to Reproduce

Try to visit "Setup & Installing": https://github.com/spikespaz/search-deflector/wiki/Setup-&-Installing

## Expected Behavior

It works.

**Comment by spikespaz** [comment]
This page is currently inaccessible because it does not exist. The new installer should be sufficiently intelligible to new users. If you need a guide for installing Legacy versions of the program, see the archived page on the sidebar.

https://github.com/spikespaz/search-deflector/wiki/Setup-&-Installing-(Legacy)

**Comment by susan-see** [comment]
I have the same problem.  The Setup & Installing info doesn't seem to exist, yet the readme.md file tells me to look at it.  Spikespaz - you say "The new installer should be sufficiently intelligible to new users."  I do not know what "the new installer" is.  I downloaded the zip file but it doesn't contain an installer that I recognize.   How do I install it?  Thank you!
