### ISSUE TITLE
Add browser selection feature.

### ISSUE THREAD

**Issue by xmha97** [spikespaz/search-deflector#71]
Hello, After installation, I can't pin the app icon to start menu
![Start menu](https://user-images.githubusercontent.com/23485114/85649884-7c5e9600-b6b9-11ea-9074-bbf61be3dd41.gif)
I think the problem is with the installer.

**Comment by spikespaz** [comment]
This is intentional. There is a line in the installer that disables pinning to start menu, because the configuration tool should not be used often (especially as ugly as it is). Why do you want to do this?

**Comment by xmha97** [comment]
I using Firefox.
My brother using Chrome.
Every time we work with a laptop, we have to change the default browser.
Please add browser selection feature.
![image](https://user-images.githubusercontent.com/23485114/85774496-25e26d80-b734-11ea-9519-b39e8b31c689.png)
Thanks.

**Comment by spikespaz** [comment]
Such a feature is unnecessary for the reason that there are already options available to you to make this easier. Firstly, if you are two different people you could be using two different Microsoft accounts on the computer, or using Chrome or Firefox user profiles to differentiate your user preferences, extensions, and other personal data. This is purely opinion but using two different browsers to accomplish a function that is provided by both of them separately as well as the operating system is quite silly. Secondly, SD also provides two different options for supporting this, the latter option for separate profiles introduced just yesterday in 1.2.0 although this may not be what you are looking for. Turning the profiles feature off will make SD launch the search term to the last selected window, which I believe is likely what you want.

Or you and your brother should just use separate Windows accounts as the OS was designed. Remember to "register for all users" when installing on another user account.

I will make the icon pinnable in later versions but I won't push it out immediately because it is not priority and there are other changes that need to be made soon anyway.

**Comment by xmha97** [comment]
Thanks for your explanation. 🙏
I think you are right and using separate Windows accounts is the best choice.
I close this issue.
